CREATE DATABASE TASK_MANAGEMENT; 
USE DATABASE TASK_MANAGEMENT; 

CREATE TABLE WORKER
(
ID INT IDENTITY(1,1) PRIMARY KEY , 
WORKER_ID INT , 
FIRST_NAME NVARCHAR(50), 
LAST_NAME NVARCHAR(50), 
USER_NAME NVARCHAR(50), 
EMAIL	NVARCHAR(50), 
PHONE 	NVARCHAR(15), 
IS_ACTIVE BIT  DEFAULT 1
); 

CREATE TABLE TASK_TYPE 
(
ID INT IDENTITY(1,1) PRIMARY KEY , 
NAME NVARCHAR(50),
IS_ACTIVE BIT  DEFAULT 1
)

CREATE TABLE TASK
(
ID INT IDENTITY(1,1) PRIMARY KEY , 
TASK_TYPE_ID INT FOREIGN KEY REFERENCES TASK_TYPE(ID) , 
TASK_DATE DATE, 
TASK_DESCRIPTION NVARCHAR(255)
)

CREATE TABLE TASK_ASSIGNMENT 
(
ID INT IDENTITY(1,1) PRIMARY KEY , 
TASK_ID  INT FOREIGN KEY REFERENCES TASK(ID),
WORKER_ID INT FOREIGN KEY REFERENCES WORKER(ID) 
);



