//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TASK_MANAGEMENTEntities : DbContext
    {
        public TASK_MANAGEMENTEntities()
            : base("name=TASK_MANAGEMENTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TASK> TASKs { get; set; }
        public virtual DbSet<TASK_ASSIGNMENT> TASK_ASSIGNMENT { get; set; }
        public virtual DbSet<TASK_TYPE> TASK_TYPE { get; set; }
        public virtual DbSet<WORKER> WORKERs { get; set; }
    }
}
