//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK_ASSIGNMENT
    {
        public int ID { get; set; }
        public Nullable<int> TASK_ID { get; set; }
        public Nullable<int> WORKER_ID { get; set; }
    
        public virtual TASK TASK { get; set; }
        public virtual WORKER WORKER { get; set; }
    }
}
