//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TASK()
        {
            this.TASK_ASSIGNMENT = new HashSet<TASK_ASSIGNMENT>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TASK_TYPE_ID { get; set; }
        public Nullable<System.DateTime> TASK_DATE { get; set; }
        public string TASK_DESCRIPTION { get; set; }
    
        public virtual TASK_TYPE TASK_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK_ASSIGNMENT> TASK_ASSIGNMENT { get; set; }
    }
}
